# Generated by Django 5.0.6 on 2026-09-05 08:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExplanationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40)),
                ('code', models.TextField()),
                ('language', models.CharField(choices=[('javascript', 'JavaScript'), ('typescript', 'TypeScript'), ('python', 'Python'), ('java', 'Java'), ('go', 'Go'), ('rust', 'Rust'), ('c', 'C'), ('cpp', 'C++'), ('csharp', 'C#'), ('php', 'PHP'), ('ruby', 'Ruby'), ('swift', 'Swift'), ('kotlin', 'Kotlin'), ('sql', 'SQL'), ('bash', 'Bash'), ('html', 'HTML'), ('css', 'CSS')], max_length=20)),
                ('input_hash', models.CharField(db_index=True, max_length=64)),
                ('explanation', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('tokens_used', models.PositiveIntegerField(blank=True, null=True)),
                ('cache_hit', models.BooleanField(default=False)),
                ('model_used', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'explanation_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_key', '-created_at'], name='explanation_session_70f469_idx'), models.Index(fields=['input_hash', 'status'], name='explanation_input_h_92ad2d_idx')],
            },
        ),
    ]
